apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           upstream
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        loadbalance
        loop
        reload
        
    }
    global:53 {
        errors
        cache 30
        proxy . $(kubectl -n istio-system get svc istiocoredns -o jsonpath={.spec.clusterIP})
    }